name: CI

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  node-ci:
    name: Node CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actalog/node-ci@v3
  dockerfile-ci:
    name: Dockerfile CI
    needs:
      - node-ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actalog/dockerfile-ci@v2
